server:
  port: 8080
spring:
  application:
    name: etaxi
  datasource:
    url: jdbc:postgresql://localhost:5432/admin
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect:
          org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect
        # noinspection undefined
        format_sql: true
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

#logging:
#  level:
#    org:
#      springframework:
#        security:
#          trace

config:
  security:
    token-first-index: 7
    secret-key:
      5b1973e61feab8c503d02380dafac6e2b4d9c44a5415ea6d03bea77804f2dc50
    token-duration: 10000000000000
  order:
    driver-search-radius: 1000
  rabbitmq:
    exchange:
      exchange
    sms-properties:
      create-order-queue:
        create_order_queue
      payment-queue:
        payment_queue
      create-order-routing-key:
        create.order
      payment-routing-key:
        payment
    logger-properties:
      logger-queue:
        logger_queue
      logger-routing-key:
        '#'


