version: '3.1'

services:
  postgresql:
    image: postgis/postgis
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - hospital
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 
        mah0041120@gmail.com
      PGADMIN_DEFAULT_PASSWORD:
        admin
    networks:
      - hospital
  redis:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - hospital
  rabbitmq:
    image: rabbitmq:management
    ports: 
      - "15672:15672"
      - "5672:5672"
networks:
  hospital:
