server:
  port: 8282
spring:
  application:
    name: logger
  datasource:
    url: jdbc:postgresql://localhost:5434/admin
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    username: guest
    password: guest
    port: 5672

#logging:
#  level:
#    org:
#      springframework:
#        security:
#          trace

# noinspection undefined
config:
  rabbitmq:
    logger-queue:
      logger_queue
